Updating CD.yml file

diff --git a/.github/workflows/cd.yml b/.github/workflows/cd.yml
--- a/.github/workflows/cd.yml
+++ b/.github/workflows/cd.yml
@@ -1,17 +1,25 @@
 name: Deploy application
 
 on:
-  push:
+  workflow_run:
+    workflows: [CI]
+    types: [completed]
     branches:
+      - master
       - '**'
       
 jobs:
   deploy:
+    if: >
+     ${{ github.event.workflow_run.conclusion == 'success' &&
+      github.event.workflow_run.event == 'push' }}
     runs-on: ubuntu-latest
 
     steps:
       - name: Check out code
         uses: actions/checkout@v4
+        with:
+          ref: ${{ github.event.workflow_run.head_sha }}
       
       - name: Setup Terraform
         uses: hashicorp/setup-terraform@v3
@@ -38,7 +46,7 @@ jobs:
         run: |
           cd terraform
           terraform apply -auto-approve \
-            -var="branch_name=${GITHUB_REF_NAME}" \
+            -var="branch_name=${{ github.event.workflow_run.head_branch }}"
             -var="public_key_path=/home/runner/.ssh/flask-todo-key.pub" \
             -var="allowed_ssh_cidr=0.0.0.0/0"
       
@@ -65,6 +73,10 @@ jobs:
 
       - name: Deploy to EC2
         uses: appleboy/ssh-action@v1.0.3
+        env:
+          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
+          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
+          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
         with:
           host: ${{ env.PUBLIC_IP }}
           username: ubuntu
@@ -73,7 +85,21 @@ jobs:
           script: |
             sudo cloud-init status --wait
             cd /home/ubuntu/Flask-Todo-List
-            echo "IMAGE_TAG=${{ github.sha }}" > image.env
+
+            if [[ -z "$POSTGRES_USER" || -z "$POSTGRES_PASSWORD" || -z "$POSTGRES_DB" ]]; then
+              echo "::error::Database secrets are not configured."
+              exit 1
+            fi
+
+            cat > .env <<EOF
+            POSTGRES_USER=$POSTGRES_USER
+            POSTGRES_PASSWORD=$POSTGRES_PASSWORD
+            POSTGRES_DB=$POSTGRES_DB
+            EOF
+            chmod 600 .env
+            chown ubuntu:ubuntu .env
+
+            echo "IMAGE_TAG=sha-${{ github.event.workflow_run.head_sha }}" > image.env
             sudo docker compose --env-file image.env pull web
             sudo docker compose --env-file image.env up -d web
             sudo docker image prune -f
